import type {
  Property,
  Chat,
  Notification,
  CreditPack,
  CreditProduct,
  CreditReward,
  Transaction,
  ArryseStep,
  User,
} from "./types"

// ===== USUARIO MOCK =====
export const mockUser: User = {
  id: "u1",
  name: "Martin Gonzalez",
  email: "martin@viviendaya.com",
  avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
  level: "propietario",
  credits: 12,
  stats: {
    publications: 3,
    saved: 7,
    permutas: 1,
    likes: 45,
  },
  properties: ["p1", "p3", "p5"],
  isLoggedIn: true,
}

// ===== PROPIEDADES MOCK =====
export const mockProperties: Property[] = [
  {
    id: "p1",
    title: "Casa moderna en Palermo",
    operation: "venta",
    type: "casa",
    condition: "a-estrenar",
    price: 185000,
    currency: "USD",
    location: {
      province: "Buenos Aires",
      city: "CABA",
      neighborhood: "Palermo",
      lat: -34.5875,
      lng: -58.4311,
    },
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    area: 220,
    features: ["garage", "patio", "parrilla", "pileta"],
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=1400&fit=crop",
    arryseVerified: true,
    arryseMode: "clasico",
    owner: {
      id: "u1",
      name: "Martin Gonzalez",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
      level: "propietario",
      verified: true,
    },
    matchPercentage: 94,
    isHighlighted: true,
    likes: 127,
    views: 1843,
    createdAt: "2026-02-25",
  },
  {
    id: "p2",
    title: "Depto luminoso en Belgrano",
    operation: "alquiler",
    type: "departamento",
    condition: "muy-bueno",
    price: 450000,
    currency: "ARS",
    location: {
      province: "Buenos Aires",
      city: "CABA",
      neighborhood: "Belgrano",
      lat: -34.5611,
      lng: -58.4576,
    },
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    area: 75,
    features: ["balcon", "luminoso", "cocina-integrada"],
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=1400&fit=crop",
    arryseVerified: true,
    arryseMode: "express",
    owner: {
      id: "u2",
      name: "Lucia Fernandez",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
      level: "propietario-plus",
      verified: true,
    },
    matchPercentage: 87,
    isHighlighted: false,
    likes: 89,
    views: 1200,
    createdAt: "2026-02-27",
  },
  {
    id: "p3",
    title: "Cabana en Bariloche con vista al lago",
    operation: "temporario",
    type: "cabana",
    condition: "muy-bueno",
    price: 120,
    currency: "USD",
    location: {
      province: "Rio Negro",
      city: "Bariloche",
      neighborhood: "Llao Llao",
      lat: -41.0515,
      lng: -71.5468,
    },
    rooms: 4,
    bedrooms: 2,
    bathrooms: 1,
    area: 95,
    features: ["chimenea", "vista-lago", "deck", "parrilla"],
    imageUrl: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&h=1400&fit=crop",
    arryseVerified: true,
    arryseMode: "pro",
    owner: {
      id: "u1",
      name: "Martin Gonzalez",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
      level: "propietario",
      verified: true,
    },
    matchPercentage: 78,
    isHighlighted: true,
    likes: 234,
    views: 3120,
    createdAt: "2026-02-20",
  },
  {
    id: "p4",
    title: "PH reciclado en Villa Crespo",
    operation: "venta",
    type: "ph",
    condition: "a-estrenar",
    price: 145000,
    currency: "USD",
    location: {
      province: "Buenos Aires",
      city: "CABA",
      neighborhood: "Villa Crespo",
      lat: -34.5985,
      lng: -58.4377,
    },
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    area: 110,
    features: ["terraza", "parrilla", "doble-altura", "luminoso"],
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=1400&fit=crop",
    arryseVerified: true,
    arryseMode: "clasico",
    owner: {
      id: "u3",
      name: "Carlos Inmobiliaria",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
      level: "inmobiliaria",
      verified: true,
    },
    matchPercentage: 91,
    isHighlighted: false,
    likes: 56,
    views: 890,
    createdAt: "2026-02-28",
  },
  {
    id: "p5",
    title: "Quinta con pileta en Pilar",
    operation: "venta",
    type: "quinta",
    condition: "bueno",
    price: 320000,
    currency: "USD",
    location: {
      province: "Buenos Aires",
      city: "Pilar",
      neighborhood: "Del Viso",
      lat: -34.4301,
      lng: -58.7993,
    },
    rooms: 7,
    bedrooms: 4,
    bathrooms: 3,
    area: 450,
    features: ["pileta", "garage-doble", "quincho", "jardin", "seguridad"],
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=1400&fit=crop",
    arryseVerified: true,
    arryseMode: "pro",
    owner: {
      id: "u1",
      name: "Martin Gonzalez",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
      level: "propietario",
      verified: true,
    },
    matchPercentage: 72,
    isHighlighted: false,
    likes: 178,
    views: 2400,
    createdAt: "2026-02-15",
  },
  {
    id: "p6",
    title: "Monoambiente premium en Puerto Madero",
    operation: "alquiler",
    type: "departamento",
    condition: "a-estrenar",
    price: 800000,
    currency: "ARS",
    location: {
      province: "Buenos Aires",
      city: "CABA",
      neighborhood: "Puerto Madero",
      lat: -34.6118,
      lng: -58.3631,
    },
    rooms: 1,
    bedrooms: 1,
    bathrooms: 1,
    area: 42,
    features: ["amenities", "seguridad", "vista-rio", "gym"],
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=1400&fit=crop",
    arryseVerified: false,
    owner: {
      id: "u4",
      name: "Sofia Torres",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face",
      level: "basico",
      verified: false,
    },
    matchPercentage: 65,
    isHighlighted: false,
    likes: 34,
    views: 560,
    createdAt: "2026-03-01",
  },
  {
    id: "p7",
    title: "Casa con jardin en Cordoba capital",
    operation: "permuta",
    type: "casa",
    condition: "bueno",
    price: 95000,
    currency: "USD",
    location: {
      province: "Cordoba",
      city: "Cordoba",
      neighborhood: "Nueva Cordoba",
      lat: -31.4235,
      lng: -64.1857,
    },
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    features: ["jardin", "garage", "patio", "cerca-centro"],
    imageUrl: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=1400&fit=crop",
    arryseVerified: true,
    arryseMode: "clasico",
    owner: {
      id: "u5",
      name: "Roberto Diaz",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
      level: "propietario",
      verified: true,
    },
    matchPercentage: 83,
    isHighlighted: true,
    likes: 92,
    views: 1567,
    createdAt: "2026-02-22",
  },
  {
    id: "p8",
    title: "Loft industrial en San Telmo",
    operation: "venta",
    type: "departamento",
    condition: "muy-bueno",
    price: 110000,
    currency: "USD",
    location: {
      province: "Buenos Aires",
      city: "CABA",
      neighborhood: "San Telmo",
      lat: -34.6215,
      lng: -58.3716,
    },
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    area: 65,
    features: ["doble-altura", "terraza", "luminoso", "reciclado"],
    imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=1400&fit=crop",
    arryseVerified: true,
    arryseMode: "express",
    owner: {
      id: "u6",
      name: "Ana Vera",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face",
      level: "propietario-plus",
      verified: true,
    },
    matchPercentage: 89,
    isHighlighted: false,
    likes: 145,
    views: 2100,
    createdAt: "2026-02-26",
  },
  {
    id: "p9",
    title: "Terreno en zona norte",
    operation: "venta",
    type: "terreno",
    condition: "bueno",
    price: 55000,
    currency: "USD",
    location: {
      province: "Buenos Aires",
      city: "Tigre",
      neighborhood: "Nordelta",
      lat: -34.4051,
      lng: -58.6510,
    },
    rooms: 0,
    bedrooms: 0,
    bathrooms: 0,
    area: 800,
    features: ["barrio-cerrado", "seguridad", "club-house", "laguna"],
    imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=1400&fit=crop",
    arryseVerified: true,
    arryseMode: "express",
    owner: {
      id: "u3",
      name: "Carlos Inmobiliaria",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
      level: "inmobiliaria",
      verified: true,
    },
    matchPercentage: 60,
    isHighlighted: true,
    likes: 67,
    views: 980,
    createdAt: "2026-02-18",
  },
  {
    id: "p10",
    title: "Departamento con vista al mar en Mar del Plata",
    operation: "temporario",
    type: "departamento",
    condition: "muy-bueno",
    price: 85,
    currency: "USD",
    location: {
      province: "Buenos Aires",
      city: "Mar del Plata",
      neighborhood: "Playa Grande",
      lat: -38.0174,
      lng: -57.5339,
    },
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    area: 80,
    features: ["vista-mar", "balcon", "cochera", "amenities"],
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=1400&fit=crop",
    arryseVerified: true,
    arryseMode: "clasico",
    owner: {
      id: "u7",
      name: "Paula Martinez",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face",
      level: "propietario",
      verified: true,
    },
    matchPercentage: 76,
    isHighlighted: false,
    likes: 203,
    views: 2890,
    createdAt: "2026-02-23",
  },
]

// ===== CHATS MOCK =====
export const mockChats: Chat[] = [
  {
    id: "c1",
    contactName: "Lucia Fernandez",
    contactAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
    lastMessage: "Hola! Cuando puedo ir a ver el depto?",
    timestamp: "14:30",
    unread: 2,
    propertyId: "p2",
  },
  {
    id: "c2",
    contactName: "Carlos Inmobiliaria",
    contactAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
    lastMessage: "Tengo una oferta interesante para tu propiedad",
    timestamp: "12:15",
    unread: 1,
    propertyId: "p1",
  },
  {
    id: "c3",
    contactName: "Roberto Diaz",
    contactAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
    lastMessage: "Me interesa la permuta! Hablamos?",
    timestamp: "Ayer",
    unread: 0,
    propertyId: "p7",
  },
  {
    id: "c4",
    contactName: "Ana Vera",
    contactAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face",
    lastMessage: "Perfecto, nos vemos el sabado",
    timestamp: "Ayer",
    unread: 0,
  },
]

// ===== NOTIFICACIONES MOCK =====
export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "like",
    title: "Tu propiedad recibio 10 likes",
    description: "Casa moderna en Palermo llego a 127 likes",
    timestamp: "Hace 2h",
    read: false,
  },
  {
    id: "n2",
    type: "match",
    title: "Nuevo match de permuta!",
    description: "Roberto Diaz quiere permutar su casa en Cordoba",
    timestamp: "Hace 5h",
    read: false,
  },
  {
    id: "n3",
    type: "credit",
    title: "Ganaste 1 credito",
    description: "Verificacion ARRYSE completada exitosamente",
    timestamp: "Ayer",
    read: true,
  },
  {
    id: "n4",
    type: "arryse",
    title: "Video ARRYSE aprobado",
    description: "Tu video de Cabana en Bariloche ya esta en el feed",
    timestamp: "Hace 2 dias",
    read: true,
  },
  {
    id: "n5",
    type: "system",
    title: "Bienvenido a Vivienda Ya!",
    description: "Completa tu perfil y gana 2 creditos gratis",
    timestamp: "Hace 3 dias",
    read: true,
  },
]

// ===== PACKS DE CREDITOS =====
export const creditPacks: CreditPack[] = [
  {
    id: "pack-1",
    name: "1 Credito",
    credits: 1,
    priceUSD: 1.25,
    pricePerCredit: 1.25,
    savings: "",
  },
  {
    id: "pack-5",
    name: "Starter",
    credits: 5,
    priceUSD: 5.0,
    pricePerCredit: 1.0,
    savings: "20%",
  },
  {
    id: "pack-10",
    name: "Growth",
    credits: 10,
    priceUSD: 9.0,
    pricePerCredit: 0.9,
    savings: "28%",
    popular: true,
  },
  {
    id: "pack-50",
    name: "Pro",
    credits: 50,
    priceUSD: 40.0,
    pricePerCredit: 0.8,
    savings: "36%",
  },
]

// ===== PRODUCTOS (en que gastar creditos) =====
export const creditProducts: CreditProduct[] = [
  {
    id: "prod-destacar",
    name: "Destacar 24h",
    cost: 1,
    description: "Tu propiedad aparece en la seccion Destacados arriba del feed",
    duration: "24 horas",
    icon: "star",
    category: "visibilidad",
  },
  {
    id: "prod-push",
    name: "Push notification",
    cost: 2,
    description: "Notificacion push a usuarios con match mayor a 70%",
    duration: "Instantaneo",
    icon: "bell",
    category: "visibilidad",
  },
  {
    id: "prod-repost",
    name: "Repost automatico",
    cost: 1,
    description: "Tu publicacion vuelve como Nueva cada 7 dias",
    duration: "Recurrente",
    icon: "repeat",
    category: "visibilidad",
  },
  {
    id: "prod-prioridad",
    name: "Prioridad en busqueda",
    cost: 2,
    description: "Apareces primero en filtros de tu zona y tipo",
    duration: "7 dias",
    icon: "arrow-up",
    category: "visibilidad",
  },
  {
    id: "prod-badge",
    name: "Badge Disponible Ya",
    cost: 1,
    description: "Muestra calendario de disponibilidad inmediata",
    duration: "7 dias",
    icon: "check-circle",
    category: "visibilidad",
  },
  {
    id: "prod-stats",
    name: "Estadisticas avanzadas",
    cost: 3,
    description: "Dashboard: quien vio, desde donde, comparacion de zona",
    duration: "30 dias",
    icon: "bar-chart",
    category: "herramientas",
  },
  {
    id: "prod-ia",
    name: "Respuesta automatica IA",
    cost: 2,
    description: "Chatbot que responde consultas cuando no estas",
    duration: "30 dias",
    icon: "bot",
    category: "herramientas",
  },
  {
    id: "prod-video-largo",
    name: "Video galeria >30seg",
    cost: 1,
    description: "Publicar video de galeria de mas de 30 segundos",
    duration: "Permanente",
    icon: "video",
    category: "biblioteca",
  },
  {
    id: "prod-slot",
    name: "Slot de biblioteca",
    cost: 1,
    description: "Guardar un video en borradores",
    duration: "30 dias",
    icon: "folder",
    category: "biblioteca",
  },
  {
    id: "prod-extension",
    name: "Extension de slot",
    cost: 1,
    description: "Renovar slot de biblioteca por 30 dias mas",
    duration: "30 dias",
    icon: "clock",
    category: "biblioteca",
  },
  {
    id: "prod-pack5",
    name: "Pack 5 slots",
    cost: 4,
    description: "Guardar hasta 5 videos simultaneos en biblioteca",
    duration: "30 dias c/u",
    icon: "folders",
    category: "biblioteca",
  },
  {
    id: "prod-pack10",
    name: "Pack 10 slots",
    cost: 7,
    description: "Guardar hasta 10 videos simultaneos en biblioteca",
    duration: "30 dias c/u",
    icon: "archive",
    category: "biblioteca",
  },
]

// ===== RECOMPENSAS (ganar creditos gratis) =====
export const creditRewards: CreditReward[] = [
  { id: "r1", action: "Verificacion ARRYSE", reward: 1, condition: "Primera verificacion GPS exitosa", limit: "1 por propiedad" },
  { id: "r2", action: "Invitar amigo", reward: 2, condition: "El invitado completa registro", limit: "Sin limite" },
  { id: "r3", action: "Primera publicacion", reward: 1, condition: "Publicar primera propiedad", limit: "1 vez" },
  { id: "r4", action: "10 likes en 1 video", reward: 1, condition: "Acumular 10 likes en un video", limit: "1 por video" },
  { id: "r5", action: "Compartir en redes", reward: 1, condition: "Link verificado en redes sociales", limit: "1 por semana" },
  { id: "r6", action: "Completar perfil 100%", reward: 2, condition: "Foto + datos + verificacion", limit: "1 vez" },
  { id: "r7", action: "Review de visita", reward: 1, condition: "Escribir review despues de visitar", limit: "1 por visita" },
  { id: "r8", action: "Racha 7 dias", reward: 1, condition: "Usar la app 7 dias seguidos", limit: "1 por semana" },
  { id: "r9", action: "Subir de nivel", reward: 3, condition: "Pasar al siguiente nivel de usuario", limit: "1 por nivel" },
]

// ===== TRANSACCIONES MOCK =====
export const mockTransactions: Transaction[] = [
  { id: "t1", type: "recompensa", description: "Verificacion ARRYSE - Casa Palermo", amount: 1, date: "2026-02-28", balanceAfter: 12 },
  { id: "t2", type: "gasto", description: "Destacar 24h - Cabana Bariloche", amount: -1, date: "2026-02-27", balanceAfter: 11 },
  { id: "t3", type: "compra", description: "Pack Growth (10 creditos)", amount: 10, date: "2026-02-25", balanceAfter: 12 },
  { id: "t4", type: "recompensa", description: "Primera publicacion", amount: 1, date: "2026-02-20", balanceAfter: 2 },
  { id: "t5", type: "recompensa", description: "Completar perfil 100%", amount: 2, date: "2026-02-18", balanceAfter: 1 },
  { id: "t6", type: "gasto", description: "ARRYSE Pro - Quinta Pilar", amount: -5, date: "2026-02-15", balanceAfter: -1 },
]

// ===== PASOS ARRYSE =====
export const arryseSteps: ArryseStep[] = [
  { id: 1, label: "Entrada", instruction: "Graba la entrada principal de la propiedad", duration: 15, icon: "door-open" },
  { id: 2, label: "Living", instruction: "Muestra el living o sala principal", duration: 20, icon: "sofa" },
  { id: 3, label: "Cocina", instruction: "Recorre la cocina completa", duration: 15, icon: "cooking-pot" },
  { id: 4, label: "Dormitorio", instruction: "Muestra el dormitorio principal", duration: 15, icon: "bed" },
  { id: 5, label: "Bano", instruction: "Graba el bano principal", duration: 10, icon: "bath" },
  { id: 6, label: "Exterior", instruction: "Muestra el balcon, patio o terraza", duration: 15, icon: "trees" },
]

// ===== DATOS DE BUSQUEDA =====
export const provinces = [
  "Buenos Aires", "CABA", "Cordoba", "Santa Fe", "Mendoza", "Tucuman",
  "Rio Negro", "Neuquen", "Salta", "Misiones", "Entre Rios", "Chubut",
]

export const citiesByProvince: Record<string, string[]> = {
  "Buenos Aires": ["La Plata", "Mar del Plata", "Pilar", "Tigre", "San Isidro", "Vicente Lopez", "Quilmes"],
  "CABA": ["CABA"],
  "Cordoba": ["Cordoba", "Carlos Paz", "Alta Gracia", "Rio Cuarto"],
  "Santa Fe": ["Rosario", "Santa Fe", "Rafaela"],
  "Mendoza": ["Mendoza", "San Rafael", "Godoy Cruz"],
  "Rio Negro": ["Bariloche", "Viedma", "General Roca"],
}

export const neighborhoodsByCity: Record<string, string[]> = {
  "CABA": ["Palermo", "Belgrano", "Recoleta", "San Telmo", "Puerto Madero", "Villa Crespo", "Caballito", "Nuñez"],
  "Pilar": ["Del Viso", "Pilar Centro", "Manuel Alberti"],
  "Bariloche": ["Centro", "Llao Llao", "Cerro Catedral", "Circuito Chico"],
  "Mar del Plata": ["Centro", "Playa Grande", "Guemes", "La Perla"],
  "Cordoba": ["Nueva Cordoba", "Centro", "Cerro de las Rosas", "Chateau"],
}

export const featureOptions = [
  "garage", "patio", "pileta", "parrilla", "balcon", "terraza",
  "luminoso", "seguridad", "amenities", "gym", "cochera",
  "vista-mar", "vista-lago", "vista-rio", "quincho", "jardin",
  "doble-altura", "cocina-integrada", "chimenea", "deck",
]

// ===== NIVELES DE USUARIO =====
export const userLevels = [
  { level: "visitante", label: "Visitante", minPublications: 0, color: "gray" },
  { level: "basico", label: "Basico", minPublications: 0, color: "blue" },
  { level: "propietario", label: "Propietario", minPublications: 1, color: "green" },
  { level: "propietario-plus", label: "Propietario+", minPublications: 3, color: "emerald" },
  { level: "inmobiliaria", label: "Inmobiliaria", minPublications: 5, color: "gold" },
  { level: "top", label: "TOP", minPublications: 10, color: "gold" },
] as const
